import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { ArrowRight, FileText } from "lucide-react"

export default function FAQPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <header className="sticky top-0 z-10 border-b bg-background/95 backdrop-blur">
        <div className="container flex h-16 items-center justify-between py-4">
          <div className="flex items-center gap-2 font-bold">
            <Link href="/" className="flex items-center gap-2">
              <FileText className="h-5 w-5" />
              <span>Co-Founder Agreement Generator</span>
            </Link>
          </div>
          <nav className="flex items-center gap-4">
            <Link href="/about" className="text-sm font-medium text-muted-foreground hover:text-foreground">
              About
            </Link>
            <Link href="/faq" className="text-sm font-medium">
              FAQ
            </Link>
            <Link href="/generator">
              <Button>Get Started</Button>
            </Link>
          </nav>
        </div>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="mx-auto max-w-3xl space-y-8">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Frequently Asked Questions
                </h1>
                <p className="text-muted-foreground md:text-xl">
                  Common questions about co-founder agreements and our generator.
                </p>
              </div>

              <Accordion type="single" collapsible className="w-full">
                <AccordionItem value="item-1">
                  <AccordionTrigger>When should we create a co-founder agreement?</AccordionTrigger>
                  <AccordionContent>
                    <p className="text-muted-foreground">
                      Ideally, you should create a co-founder agreement as early as possible in your startup journey,
                      preferably before you start working together or immediately after deciding to form a company.
                      Having clear agreements in place from the beginning helps prevent misunderstandings and conflicts
                      later on.
                    </p>
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem value="item-2">
                  <AccordionTrigger>Is this agreement legally binding?</AccordionTrigger>
                  <AccordionContent>
                    <p className="text-muted-foreground">
                      The agreement generated by our tool is designed to be legally binding when properly executed by
                      all parties. However, we strongly recommend having the final document reviewed by a qualified
                      attorney in your jurisdiction before signing. Legal requirements vary by location, and certain
                      provisions may need to be adjusted to comply with local laws.
                    </p>
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem value="item-3">
                  <AccordionTrigger>
                    What's the difference between equal and custom equity distribution?
                  </AccordionTrigger>
                  <AccordionContent>
                    <p className="text-muted-foreground">
                      Equal equity distribution means each co-founder receives the same percentage of ownership in the
                      company. Custom equity distribution allows you to assign different percentages to each co-founder
                      based on factors like capital contribution, experience, role, and commitment level. Research shows
                      that equal splits are common but not always optimal, especially when founders contribute
                      differently to the venture.
                    </p>
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem value="item-4">
                  <AccordionTrigger>Why is vesting important in a co-founder agreement?</AccordionTrigger>
                  <AccordionContent>
                    <p className="text-muted-foreground">
                      Vesting schedules protect all co-founders by ensuring that equity is earned over time rather than
                      granted all at once. This prevents situations where a co-founder leaves early but retains a large
                      equity stake without having contributed proportionally to the company's growth. Typical vesting
                      schedules include a one-year cliff (no equity vests until after one year) followed by monthly or
                      quarterly vesting over 3-4 years.
                    </p>
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem value="item-5">
                  <AccordionTrigger>Can we modify the agreement after it's been signed?</AccordionTrigger>
                  <AccordionContent>
                    <p className="text-muted-foreground">
                      Yes, co-founder agreements can be modified after signing, but all parties must agree to the
                      changes and sign an amendment or a new agreement. It's important to document any changes properly
                      to ensure they're legally binding. As your startup evolves, it's good practice to review your
                      co-founder agreement periodically to ensure it still reflects your current situation and
                      intentions.
                    </p>
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem value="item-6">
                  <AccordionTrigger>What happens if a co-founder wants to leave the company?</AccordionTrigger>
                  <AccordionContent>
                    <p className="text-muted-foreground">
                      Your co-founder agreement should specify what happens when a co-founder exits, including how
                      unvested equity is handled, whether the company or other founders have the right to buy back
                      shares, and how the departing founder's value is calculated. The agreement typically includes
                      provisions for voluntary departure, termination for cause, death, or disability. Having these
                      provisions in place helps ensure a smooth transition and protects both the company and the
                      departing founder.
                    </p>
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem value="item-7">
                  <AccordionTrigger>Is this agreement suitable for all types of businesses?</AccordionTrigger>
                  <AccordionContent>
                    <p className="text-muted-foreground">
                      Our co-founder agreement generator is designed primarily for startups and small businesses with
                      multiple founders. It can be used for various business structures including LLCs, corporations,
                      and partnerships. However, certain industries with specific regulatory requirements (like
                      healthcare or financial services) may need additional specialized provisions. If your business
                      operates in a highly regulated industry, we recommend consulting with a specialized attorney after
                      generating your initial agreement.
                    </p>
                  </AccordionContent>
                </AccordionItem>
              </Accordion>

              <div className="flex justify-center">
                <Link href="/generator">
                  <Button size="lg" className="gap-2">
                    Create Your Agreement <ArrowRight className="h-4 w-4" />
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="border-t bg-muted/50">
        <div className="container flex flex-col gap-4 py-10 md:flex-row md:justify-between">
          <div className="flex flex-col gap-2">
            <div className="flex items-center gap-2 font-bold">
              <FileText className="h-5 w-5" />
              <span>Co-Founder Agreement Generator</span>
            </div>
            <p className="text-sm text-muted-foreground">
              Creating legally sound co-founder agreements to help startups succeed.
            </p>
          </div>
          <div className="flex flex-col gap-2 text-sm">
            <p className="font-medium">Legal Disclaimer</p>
            <p className="text-muted-foreground">
              This tool provides general information and is not a substitute for legal advice.
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}
